---

- name: Create EFI partition
  community.general.parted:
    device: "{{ device }}"
    number: "{{ efi_number }}"
    state: present
    label: gpt
    flags: [esp]
    part_start: "{{ part_start_efi_size }}"
    part_end: "{{ part_end_efi_size }}"
  when: layout == "uefi"

- name: Format EFI partition
  community.general.filesystem:
    fstype: vfat
    dev: "{{ device }}{{ efi_number }}"
  when: layout == "uefi"

- name: Create swap partition
  community.general.parted:
    device: "{{ device }}"
    number: "{{ swap_number }}"
    state: present
    label: gpt
    flags: [swap]
    part_start: "{{ part_start_swap_size }}"
    part_end: "{{ part_end_swap_size }}"

- name: Format swap partition
  community.general.filesystem:
    fstype: swap
    dev: "{{ device }}{{ swap_number }}"

- name: Create root partition
  community.general.parted:
    device: "{{ device }}"
    number: "{{ root_number }}"
    state: present
    label: gpt
    flags: [boot]
    part_start: "{{ part_start_root_size }}"
    part_end: "{{ part_end_root_size }}"

- name: Format root partition
  community.general.filesystem:
    fstype: ext4
    dev: "{{ device }}{{ root_number }}"

- name: Mount root partition
  ansible.builtin.mount:
    path: /mnt
    src: "{{ device }}{{ root_number }}"
    state: mounted
    fstype: ext4

- name: Create /mnt/boot directory
  ansible.builtin.file:
    path: /mnt/boot
    state: directory
    mode: 0755
    owner: root
    group: root
    recurse: yes
    selevel: s0
    serole: object_r
    setype: sysfs_t
    seuser: system_u
  when: layout == "uefi"

- name: Mount EFI partition
  ansible.builtin.mount:
    path: /mnt/boot
    src: "{{ device }}{{ efi_number }}"
    state: mounted
    fstype: vfat
  when: layout == "uefi"

- name: Swapon swap partition
  ansible.builtin.shell:
    cmd: swapon "{{ device }}""{{ swap_number}}"
